version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: market_place_drf
    container_name: cmarket_place_drf_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=market_place_drf.settings.dev
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./keys/:/app/keys
      - ./fixtures/:/app/fixtures
      - ./media/:/app/media
      - ./staticfiles/:/app/staticfiles
    command: /start-server

  db:
      image: postgres:14.6-alpine
      env_file:
        - .env
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "db_name"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5
      volumes:
        - ./pddata:/var/lib/postgresql/data

  api:
    build:
      context: .
    tty: false
    volumes:
      - .:/code
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  api:
  db:
    driver: local